apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-was
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-was
        image: 117612009356.dkr.ecr.ap-northeast-2.amazonaws.com/django:v2
        ports:
        - containerPort: 8000
      nodeSelector:
        eks.amazonaws.com/nodegroup: nodegroup-was
