# Generated by Django 3.1 on 2022-09-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('shortcon', models.TextField(max_length=30)),
                ('content', models.TextField()),
                ('pubdate', models.DateTimeField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('viewcount', models.IntegerField(default=0)),
                ('sellcount', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('cate', models.CharField(choices=[('ELC', '가전'), ('FOD', '음식'), ('CLO', '의류'), ('LIV', '생필품')], max_length=3)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='acc.user')),
            ],
        ),
    ]
