# Generated by Django 4.0.3 on 2022-10-03 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lishortcon', models.TextField(max_length=20)),
                ('licontent', models.TextField()),
                ('pubdate', models.DateTimeField()),
                ('video', models.FileField(upload_to='live/')),
                ('viewcount', models.IntegerField(default=0)),
                ('sellcount', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('cate', models.CharField(choices=[('ELC', '가전'), ('FOD', '음식'), ('CLO', '의류'), ('LIV', '생필품')], max_length=3)),
                ('liseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liseller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livecomment', models.TextField()),
                ('retitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live.live')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
