# Generated by Django 4.0.3 on 2022-10-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_rename_retitle_reply_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='live',
            old_name='licontent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='live',
            old_name='liseller',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='live',
            old_name='lishortcon',
            new_name='shortcon',
        ),
    ]
